### PR TITLE
Coerce character

### PR DESCRIPTION
**Pull request by kbenoit**
Make it so that quanteda v2 corpus objects work with tokenize and parse functions, by stripping their attributes off to leave a simple, named character input.

Implements the **spacyr** side of #1884.

### CODE REVIEW

**Comment by amatsuo** [comment]
Obviously the CI builds are failing. Let me try fixing it before the merge.

**Comment by kbenoit** [comment]
Great, thanks @amatsuo

**Comment by amatsuo** [comment]
@kbenoit 
The latest commit, after removing `lintr`, was successfully built. I wasn't able to make it run:
```
Error: Test failed: 'Package Style'
* attempt to apply non-function
Backtrace:
  1. lintr::expect_lint_free()
  2. lintr::lint_package(...)
  3. lintr::lint_dir(...)
  8. base::lapply(...)
  9. lintr:::FUN(X[[i]], ...)
 10. lintr::lint(file, ..., parse_settings = FALSE, exclusions = exclusions)
 11. lintr:::flatten_lints(linters[[linter]](expr))
 13. lintr:::flatten_list(x, class = "lint")
 14. lintr:::assign_item(x)
```
If you want to keep `lintr`, please give a shot. Otherwise, I think it's ready to merge.

**Comment by kbenoit** [comment]
Thanks @amatsuo !

**Pull request merged**
