### PR TITLE
make spacy_download_langmodel work with multiple models (#249)

### PR DESCRIPTION
**Pull request by JBGruber**

### CODE REVIEW

**Comment by kbenoit** [comment]
I wonder what's happening on macOS and windows on the version install test. Maybe we should update the spaCy version that the tests are using?

**Review by kbenoit — APPROVED** [review]

**Comment by kbenoit** [comment]
@JBGruber Please increment the version by a (very) minor number in DESCRIPTION and add something to NEWS.md recording the fix.

**Comment by JBGruber** [comment]
I bumped the version and opened a new issue about the failing tests (#252).

**Comment by kbenoit** [comment]
@JBGruber feel free to create branches here rather than in your fork for future PRs

**Pull request merged**
