### PR TITLE
Rewrite of spacy_install

### PR DESCRIPTION
**Pull request by JBGruber**
Addresses #236. I use some newer functions from `reticulate` that were introduced since `spacyr` was developed. The installation process is now significantly easier (but there are also less options available for users). The default is to install `spaCy` in a virtual environment managed by  `reticulate` (after checking if a suitable Python bin is available and installing it if not).

I tested it on two Linux machines (Arch and Debian) and Windows 10+11. On the Arch machine I also installed the GPU version. Apple silicone can also be used easily. The installation worked without hiccups (once `C` dependencies and `reticulate` were updated).

I assume that most people can now run `spacy_install()` without prior knowledge or any specific setup. ~~But I still want to document how one could use a manual install by setting either `SPACY_PYTHON` or `RETICULATE_PYTHON` -- which should also be used as a troubleshooting guide.~~ I think this should be a vignette rather than the landing page of <https://spacyr.quanteda.io> (but that might be a different PR).

Let me know what you think :grin:

### CODE REVIEW

**Comment by JBGruber** [comment]
I changed the installation.rmd. Now all that is left is to adapt the tests.

**Comment by JBGruber** [comment]
Unfortunatly, it seems that `remove_symbols` does not work correctly anymore:

``` r
library(spacyr)
txt <- "This: £ = GBP! 15% not! > 20 percent?"
spacy_tokenize(txt, remove_symbols = TRUE, padding = FALSE)
#> successfully initialized (spaCy Version: 3.6.1, language model: en_core_web_sm)
#> $text1
#>  [1] "This"    ":"       "="       "GBP"     "!"       "15"      "%"      
[8] "not"     "!"       ">"       "20"      "percent" "?"
```

<sup>Created on 2023-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

This is due to an upstream change in spaCy though.

```python
import spacy
doc = nlp("This: £ = GBP! 15% not! > 20 percent?")

for t in doc:
    print(t, t.pos_)
>>>  This PRON
>>>  : PUNCT
>>>  £ PROPN
>>>  = X
>>>  GBP PROPN
>>>  ! PROPN
>>>  15 NUM
>>>  % NOUN
>>>  not PART
>>>  ! PUNCT
>>>  > X
>>>  20 NUM
>>>  percent NOUN
>>>  ? PUNCT
```
To test if something is a symbol, you use `w.pos_ == "SYM"`, which does not work anymore since `=` is now classified as `X` for some reason. I remove the test.

**Comment by JBGruber** [comment]
There are a few more inconsitencies that lead to failing tests. Where I think those have nothing to do with this PR, but instead are upstream changes, I skip them with `skip("behaviour changed in spaCy")`. Otherwise tests succeed (at least on my machine) now.

**Review by kbenoit — APPROVED** [review]
This is really welcome @JBGruber. Sorry it took me so long to get to it. I incremented the verson to 1.3. It's full of breaking changes but only to `spacy_install()`. So be it.

**Pull request merged**
